# Generated by Django 3.1.1 on 2020-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('roll_no', models.IntegerField()),
                ('course', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
